### ISSUE TITLE
State and Request

### ISSUE THREAD

**Issue by guilaureano** [guilhermelaureano/improved-youtube-search#6]
### Requirements:
- Think of a better way to perform requests and deal with the application's stored states.
---
### DOD:
- [x] Axios ~~Requests (React Query?)~~ 
- [x] Global state ( useContext, Redux, ?)
---
### ToDo:
- [x] organize request functions;
- [x] apply context
